CREATE TABLE TB_CLIENT(
name CHAR(50) NOT NULL,
age INT(2) NOT NULL,
code CHAR(30) NOT NULL,
email CHAR(50) NOT NULL,
adress CHAR(50) NOT NULL,
number CHAR(4) NOT NULL,
permission VARCHAR NOT NULL,

CONSTRAINT pk_tb_client PRIMARY KEY (code),
CHECK (age >= 16);
);

INSERT INTO TB_CLIENT VALUES('teste00', 18, '00000000000', '00@teste.com', 'T. Teste da Silva', '00', 'ADMIN');
SELECT * FROM TB_CLIENT;
