

CREATE TABLE TB_CLIENT(
name CHAR(50) NOT NULL,
age INT(2) NOT NULL,
code CHAR(30) NOT NULL,
email CHAR(50) NOT NULL,
adress CHAR(50) NOT NULL,
number CHAR(4) NOT NULL,
permission VARCHAR NOT NULL,

CONSTRAINT pk_tb_client PRIMARY KEY (code),
CHECK (age >= 16);
);
ALTER TABLE TB_PRODUCT
ALTER COLUMN price TYPE DOUBLE PRECISION;

INSERT INTO TB_CLIENT VALUES('teste00', 18, '00000000000', '00@teste.com', 'T. Teste da Silva', '00', 'ADMIN');
SELECT * FROM TB_CLIENT;
DELETE FROM TB_CLIENT WHERE code = '12345678900';

CREATE TABLE TB_PRODUCT(
name VARCHAR NOT NULL,
price INT NOT NULL,
code VARCHAR NOT NULL,
description VARCHAR,

CONSTRAINT PK_PRODUCT PRIMARY KEY (code),
CHECK (price > 0)
);

CREATE TABLE PRODUCT_STOCK(
code VARCHAR,
quantity INT NOT NULL,

CONSTRAINT FK_PRODUCT_STOCK FOREIGN KEY (code) REFERENCES TB_PRODUCT (code)
);
INSERT INTO TB_PRODUCT VALUES ('produto fixo para teste', 1000000.00, '000-000-000', 'produto fixo do banco de dados para teste');
INSERT INTO PRODUCT_STOCK VALUES ('000-000-000', 1);

SELECT * FROM PRODUCT_STOCK;
SELECT * FROM TB_PRODUCT;
DELETE FROM PRODUCT_STOCK WHERE code = '000-000-000';
DELETE FROM TB_PRODUCT WHERE code = '000-000-000';